#!/bin/bash
xkeysnail <(echo '
# -*- coding: utf-8 -*-

import re
from xkeysnail.transform import *

define_keymap(re.compile("^(gnome-)?terminal$", re.IGNORECASE), {
    # terminal-specific cut-copy-paste
    K("Super-c"): K("C-Shift-c"),
    K("Super-x"): K("C-Shift-x"),
    K("Super-v"): K("C-Shift-v"),

    # tabs and windows
    K("Super-t"): K("C-Shift-t"),
    K("Super-n"): K("C-Shift-n"),
    K("Super-w"): K("C-Shift-w"),
    K("Super-q"): K("C-Shift-q"),
})

define_keymap(re.compile(".*"), {
    # undo, copy, cut, paste
    K("Super-z"): K("C-z"),
    K("Super-c"): K("C-c"),
    K("Super-x"): K("C-x"),
    K("Super-v"): K("C-v"),

    # save, close, quit
    K("Super-s"): K("C-s"),
    K("Super-w"): K("M-f4"),
    K("Super-q"): K("C-q"),

    # text navigation
    K("Super-RIGHT"): K("END"),
    K("Super-LEFT"): K("HOME"),
    K("Super-UP"): K("C-HOME"),
    K("Super-DOWN"): K("C-END"),
    K("M-LEFT"): K("C-LEFT"),
    K("M-RIGHT"): K("C-RIGHT"),

    # text selection
    K("Super-Shift-RIGHT"): K("Shift-END"),
    K("Super-Shift-LEFT"): K("Shift-HOME"),
    K("Super-Shift-UP"): K("C-Shift-HOME"),
    K("Super-Shift-DOWN"): K("C-Shift-END"),
    K("M-Shift-LEFT"): K("C-Shift-LEFT"),
    K("M-Shift-RIGHT"): K("C-Shift-RIGHT"),

    # emacs-style text navigation
    K("C-a"): K("HOME"),
    K("C-e"): K("END"),
    K("C-w"): K("C-BACKSPACE"),
})
') > /tmp/xkeysnail.log 2>&1
